# Site settings
title:
email:
author:
description:
url:
kramdown:
  parse_block_html: true
highlighter: rouge

# Build settings
permalink: :title/
sass:
  sass_dir: css
collections:
  tutorials:
    output: true
  products:
    output: true

# Edit on GitHub
# https://gist.github.com/Eeemil/e93ad054a73037f5bea3
github_username: luxonis
git_repo: depthai-docs-website
