name: Run install dependencies script
on: [push]
jobs:
  install-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source/_static/install_dependencies.sh

  install-debian:
    runs-on: ubuntu-latest
    container: 'debian:latest'
    steps:
      - run: apt install -y sudo
      - uses: actions/checkout@v2
      - run: source/_static/install_dependencies.sh

  install-fedora:
    runs-on: ubuntu-latest
    container: 'fedora:latest'
    steps:
      - run: dnf install -y sudo
      - uses: actions/checkout@v2
      - run: source/_static/install_dependencies.sh
